Speed up build by running fewer checks (#50)
* Speed up build bu running fewer

* Suntax

* Find components automatically

* syntax

* try paralells

* use PWD

* ont use paralell

* Fail all the time

* Dont trust global evironment variable

* fix

* Added some logging

* More debug

* Use groups

* fix

* cleanup

* Try test failure

* minor

* Make sure we run all tests

* Error in group

* Use bash

* Try new stuff

* syntax

* Force run all tests

* Fixed test

* Run composer nornalize quicker

* download file with curl

* Follow redirects

* test fail compoer normalize

* More fixes

* disable xdebug

* Bugfix

* Disable code coverage

* Fixed composer.json

* Adding root tests and prefer lowest

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -10,34 +10,42 @@ jobs:
   composer-normalize:
     name: Composer Normalize
     runs-on: ubuntu-latest
-    strategy:
-      max-parallel: 10
-      matrix:
-        component: ['Core', 'S3', 'Ses', 'Sqs']
 
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v2
-
-    - name: Normalize
-      uses: "docker://ergebnis/composer-normalize-action:latest"
-      env:
-        COMPOSER_HOME: /root/.composer
+    - name: Set up PHP
+      uses: shivammathur/setup-php@1.8.1
       with:
-        args: "./src/${{ matrix.component }}/composer.json --dry-run"
+        php-version: 7.4
+        coverage: none
 
-  composer-normalize-root:
-    name: Composer Normalize Root
-    runs-on: ubuntu-latest
-
-    steps:
     - name: Checkout code
       uses: actions/checkout@v2
 
+    - name: Download
+      run: |
+        curl -L https://github.com/ergebnis/composer-normalize/releases/latest/download/composer-normalize.phar --output normalize.phar
+        chmod +x normalize.phar
+
     - name: Normalize
-      env:
-        COMPOSER_HOME: /root/.composer
-      uses: "docker://ergebnis/composer-normalize-action:latest"
+      run: |
+        ok=0
+        echo ::group::Root
+        ./normalize.phar --dry-run
+        echo ::endgroup::
+        for COMPONENT in $(find src -maxdepth 4 -type f -name composer.json | sort)
+        do
+          echo ::group::$COMPONENT
+          localExit=0
+          ./normalize.phar $COMPONENT --dry-run || localExit=1
+          ok=$(( $localExit || $ok ))
+          echo ::endgroup::
+          if [ $localExit -ne 0 ]; then
+            echo "::error::$COMPONENT failed"
+          fi
+        done
+
+        exit $ok
+
 
 #  roave-bc-check:
 #    name: Roave BC Check
diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -15,15 +15,13 @@ jobs:
       max-parallel: 10
       matrix:
         php: ['7.2', '7.3', '7.4']
-        component: ['Core', 'S3', 'Ses', 'Sqs']
 
     steps:
       - name: Set up PHP
-        uses: shivammathur/setup-php@1.7.0
+        uses: shivammathur/setup-php@1.8.1
         with:
           php-version: ${{ matrix.php }}
-          coverage: xdebug
-          ini-values: xdebug.overload_var_dump=1
+          coverage: none
           tools: prestissimo
 
       - name: Checkout code
@@ -33,14 +31,123 @@ jobs:
         run: |
           rm composer.*
           composer init --no-interaction
+
+          echo ::group::Download
           composer req symfony/phpunit-bridge
+          echo ::endgroup::
+
+          echo ::group::Install
+          ./vendor/bin/simple-phpunit install
+          echo ::endgroup::
 
       - name: Download dependencies
         run: |
-          cd "./src/${{ matrix.component }}"
-          sed -i -re 's/"async-aws\/core": "[^"]+",/"async-aws\/core": "*@dev",/' composer.json
-          sed -i -re 's/"require": \{/"repositories": [{"type": "path","url": "..\/Core"}],"require": \{/' composer.json
+          CURRENT_DIR=$(pwd)
+          for COMPONENT in $(find src -maxdepth 4 -type f -name phpunit.xml.dist -printf '%h\n' | sort)
+          do
+            echo ::group::$COMPONENT
+            echo "$CURRENT_DIR/$COMPONENT"
+            cd "$CURRENT_DIR/$COMPONENT"
+            sed -i -re 's/"async-aws\/core": "[^"]+",/"async-aws\/core": "*@dev",/' composer.json
+            sed -i -re 's/"require": \{/"repositories": [{"type": "path","url": "..\/Core"}],"require": \{/' composer.json
+            composer update --no-interaction --prefer-dist --optimize-autoloader
+            echo ::endgroup::
+          done
+
+      - name: Run tests
+        run: |
+          ok=0
+          for COMPONENT in $(find src -maxdepth 4 -type f -name phpunit.xml.dist -printf '%h\n' | sort)
+          do
+            echo ::group::$COMPONENT
+            localExit=0
+            ./vendor/bin/simple-phpunit -c ./$COMPONENT 2>&1 || localExit=1
+            ok=$(( $localExit || $ok ))
+            echo ::endgroup::
+            if [ $localExit -ne 0 ]; then
+              echo "::error::$COMPONENT failed"
+            fi
+          done
+
+          exit $ok
+
+  lowest:
+    name: Lowest dependencies
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Set up PHP
+        uses: shivammathur/setup-php@1.8.1
+        with:
+          php-version: 7.3
+          coverage: none
+          tools: prestissimo
+
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - name: Download phpunit
+        run: |
+          rm composer.*
+          composer init --no-interaction
+
+          echo ::group::Download
+          composer req symfony/phpunit-bridge
+          echo ::endgroup::
+
+          echo ::group::Install
+          ./vendor/bin/simple-phpunit install
+          echo ::endgroup::
+
+      - name: Download dependencies
+        run: |
+          CURRENT_DIR=$(pwd)
+          for COMPONENT in $(find src -maxdepth 4 -type f -name phpunit.xml.dist -printf '%h\n' | sort)
+          do
+            echo ::group::$COMPONENT
+            echo "$CURRENT_DIR/$COMPONENT"
+            cd "$CURRENT_DIR/$COMPONENT"
+            composer update --no-interaction --prefer-dist --optimize-autoloader --prefer-lowest
+            echo ::endgroup::
+          done
+
+      - name: Run tests
+        run: |
+          ok=0
+          for COMPONENT in $(find src -maxdepth 4 -type f -name phpunit.xml.dist -printf '%h\n' | sort)
+          do
+            echo ::group::$COMPONENT
+            localExit=0
+            ./vendor/bin/simple-phpunit -c ./$COMPONENT 2>&1 || localExit=1
+            ok=$(( $localExit || $ok ))
+            echo ::endgroup::
+            if [ $localExit -ne 0 ]; then
+              echo "::error::$COMPONENT failed"
+            fi
+          done
+
+          exit $ok
+
+  root:
+    name: Root tests
+    runs-on: ubuntu-latest
+    strategy:
+      max-parallel: 10
+    steps:
+      - name: Set up PHP
+        uses: shivammathur/setup-php@1.8.1
+        with:
+          php-version: 7.4
+          coverage: none
+          tools: prestissimo
+
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - name: Download dependencies
+        run: |
           composer update --no-interaction --prefer-dist --optimize-autoloader
 
       - name: Run tests
-        run: ./vendor/bin/simple-phpunit -c "./src/${{ matrix.component }}"
+        run: |
+          ./vendor/bin/simple-phpunit
