Adding root tests and prefer lowest

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -70,3 +70,84 @@ jobs:
           done
 
           exit $ok
+
+  lowest:
+    name: Lowest dependencies
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Set up PHP
+        uses: shivammathur/setup-php@1.8.1
+        with:
+          php-version: 7.3
+          coverage: none
+          tools: prestissimo
+
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - name: Download phpunit
+        run: |
+          rm composer.*
+          composer init --no-interaction
+
+          echo ::group::Download
+          composer req symfony/phpunit-bridge
+          echo ::endgroup::
+
+          echo ::group::Install
+          ./vendor/bin/simple-phpunit install
+          echo ::endgroup::
+
+      - name: Download dependencies
+        run: |
+          CURRENT_DIR=$(pwd)
+          for COMPONENT in $(find src -maxdepth 4 -type f -name phpunit.xml.dist -printf '%h\n' | sort)
+          do
+            echo ::group::$COMPONENT
+            echo "$CURRENT_DIR/$COMPONENT"
+            cd "$CURRENT_DIR/$COMPONENT"
+            composer update --no-interaction --prefer-dist --optimize-autoloader --prefer-lowest
+            echo ::endgroup::
+          done
+
+      - name: Run tests
+        run: |
+          ok=0
+          for COMPONENT in $(find src -maxdepth 4 -type f -name phpunit.xml.dist -printf '%h\n' | sort)
+          do
+            echo ::group::$COMPONENT
+            localExit=0
+            ./vendor/bin/simple-phpunit -c ./$COMPONENT 2>&1 || localExit=1
+            ok=$(( $localExit || $ok ))
+            echo ::endgroup::
+            if [ $localExit -ne 0 ]; then
+              echo "::error::$COMPONENT failed"
+            fi
+          done
+
+          exit $ok
+
+  root:
+    name: Root tests
+    runs-on: ubuntu-latest
+    strategy:
+      max-parallel: 10
+    steps:
+      - name: Set up PHP
+        uses: shivammathur/setup-php@1.8.1
+        with:
+          php-version: 7.4
+          coverage: none
+          tools: prestissimo
+
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - name: Download dependencies
+        run: |
+          composer update --no-interaction --prefer-dist --optimize-autoloader
+
+      - name: Run tests
+        run: |
+          ./vendor/bin/simple-phpunit
